## Multilayered Network
To make the network more powerful, we can stack up individual neurons into layers. The output of one layer becomes the input for the next layer.

In [30]:
import torch

In [31]:
def activation(x):
    """Create a sigmoid activation function.
    Good for outputs that fall between 0 and 1. (probability)
    args x: a torch tensor.
    """
    return 1/(1 + torch.exp(-x))

# generate some data
torch.manual_seed(7)

# features are 3 random normal variables
features = torch.randn((1, 3))

# define size of each layer in our network
n_input = features.shape[1]  # number of input units, must match number of input features
n_hidden = 2
n_output = 1

# weights for input to hidden layer
w1 = torch.randn(n_input, n_hidden)
# weights for hidden layer to output layer
w2 = torch.randn(n_hidden, n_output)

# biases for the hidden layer and the output layer
b1 = torch.randn(1, n_hidden)
b2 = torch.randn(1, n_output)

h = activation(torch.mm(features, w1) + b1)
# use h as input to the next layer
output = activation(torch.mm(h, w2) + b2)
print(output)

tensor([[0.3171]])


## numpys and tensors
We can can create tensors from numpy arrays.
The memory is shared between the Numpy array and the Tensor so a change in one will trigger a change in the other.

In [32]:
import numpy as np
a = np.random.rand(4, 3)

In [33]:
b = torch.from_numpy(a)
b

tensor([[0.8519, 0.4287, 0.9095],
        [0.7690, 0.7815, 0.7152],
        [0.7211, 0.4287, 0.8067],
        [0.4219, 0.7282, 0.3916]], dtype=torch.float64)

In [34]:
b.mul_(2)

tensor([[1.7038, 0.8573, 1.8190],
        [1.5379, 1.5630, 1.4305],
        [1.4422, 0.8574, 1.6133],
        [0.8438, 1.4564, 0.7832]], dtype=torch.float64)

In [35]:
a

array([[1.70379337, 0.85731166, 1.81903246],
       [1.53791446, 1.5629657 , 1.4304528 ],
       [1.442249  , 0.8573502 , 1.6133007 ],
       [0.84380949, 1.45637187, 0.78323228]])