In [6]:
import torch
import numpy as np

In [9]:
t = torch.Tensor()
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [13]:
# specify a GPU to do computations
device = torch.device('cuda:1')
device

device(type='cuda', index=1)

Creating Pytorch Tensors from data

In [16]:
# create a numpy array
data = np.array([1, 2, 3])
type(data)

numpy.ndarray

In [30]:
t1 = torch.Tensor(data) # constructors
t2 = torch.tensor(data) # factory function, instead of using a constructor
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [32]:
print(t1.dtype)
print(t2.dtype)
# the default data type of a tensor
torch.get_default_dtype()

torch.float32
torch.int64


torch.float32

In [35]:
# type inference: the dtype is inferred from the incoming data
torch.tensor(np.array([1, 2, 4])).dtype
# you can also explicitly set the dtype
torch.tensor(np.array([1,2,3]), dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [36]:
data

array([1, 2, 3])

## Memory: Sharing vs Copying

* When using torch.as_tensor(), the torch tensor and numpy array share the memory location.
* When using torch.tensor, torch.Tensor, we copy data into a new memory location.
* Sharing data is more efficient because the data is only written on one mem location.
* When sharing data, be careful not to inadvertently make unwanted changes in the underlying data without realizing the change impacts multiple objects Note: the memory sharing of as_tensor() does not work with built-in Python data structures like lists.

In [66]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [67]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
print(t1)
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3])


In [68]:
data[0] = 0
data[1] = 0
data[2] = 0

In [69]:
print(t1)

tensor([1., 2., 3.])


In [70]:
print(t3)

tensor([0, 0, 0])
