## Differential Privacy
The key definition of differential privacy is: 

* **Make a promise to a data subject that: You won’t be affected, adversely or otherwise, by allowing your data to be used in any analysis, no matter what studies, datasets  or information sources, are available.**

* Ensure that Network model learning from sensitive data are only learning what they are supposed to learn without accidentally learning what they are not supposed to learn from their data

In more technical terms, the question to ask yourself is:

* When querying a DB, if I remove someone from the DB, would the output of the query change? To check this we must construct **"parallet DBs"** which are simply DBs with one entry removed.

Steps:
1. Create the initial DB
2. Create all parallel DBs

In [7]:
# db
import torch

db = torch.rand(5000) > 0.5
db

tensor([ 1,  0,  0,  ...,  0,  0,  1], dtype=torch.uint8)

In [8]:
remove_index = 2

db[0:4]

tensor([ 1,  0,  0,  1], dtype=torch.uint8)

In [9]:
def get_parallel_db(db, remove_index):
    return torch.cat((db[0:remove_index], db[remove_index+1:]))


In [10]:
get_parallel_db(db, 1000)


tensor([ 1,  0,  0,  ...,  0,  0,  1], dtype=torch.uint8)

In [20]:
def get_parallel_dbs(db):
    parallel_dbs = list()
    for i in range(len(db)):
        pdb = get_parallel_db(db, i)
        parallel_dbs.append(pdb)
    return parallel_dbs

In [23]:
pdbs = get_parallel_dbs(db)

In [22]:
pdbs

[tensor([ 0,  0,  1,  ...,  0,  0,  1], dtype=torch.uint8),
 tensor([ 1,  0,  1,  ...,  0,  0,  1], dtype=torch.uint8),
 tensor([ 1,  0,  1,  ...,  0,  0,  1], dtype=torch.uint8),
 tensor([ 1,  0,  0,  ...,  0,  0,  1], dtype=torch.uint8),
 tensor([ 1,  0,  0,  ...,  0,  0,  1], dtype=torch.uint8),
 tensor([ 1,  0,  0,  ...,  0,  0,  1], dtype=torch.uint8),
 tensor([ 1,  0,  0,  ...,  0,  0,  1], dtype=torch.uint8),
 tensor([ 1,  0,  0,  ...,  0,  0,  1], dtype=torch.uint8),
 tensor([ 1,  0,  0,  ...,  0,  0,  1], dtype=torch.uint8),
 tensor([ 1,  0,  0,  ...,  0,  0,  1], dtype=torch.uint8),
 tensor([ 1,  0,  0,  ...,  0,  0,  1], dtype=torch.uint8),
 tensor([ 1,  0,  0,  ...,  0,  0,  1], dtype=torch.uint8),
 tensor([ 1,  0,  0,  ...,  0,  0,  1], dtype=torch.uint8),
 tensor([ 1,  0,  0,  ...,  0,  0,  1], dtype=torch.uint8),
 tensor([ 1,  0,  0,  ...,  0,  0,  1], dtype=torch.uint8),
 tensor([ 1,  0,  0,  ...,  0,  0,  1], dtype=torch.uint8),
 tensor([ 1,  0,  0,  ...,  0,  0,  1], 

In [25]:
def create_db_and_parallels(num_entries):
    # generate dbs and parallel dbs on the fly
    db = torch.rand(num_entries) > 0.5
    pdbs = get_parallel_dbs(db)
    
    return db, pdbs

In [26]:
db, pdbs = create_db_and_parallels(10)


In [27]:
db

tensor([ 0,  0,  1,  1,  1,  0,  1,  1,  0,  1], dtype=torch.uint8)

In [28]:
pdbs

[tensor([ 0,  1,  1,  1,  0,  1,  1,  0,  1], dtype=torch.uint8),
 tensor([ 0,  1,  1,  1,  0,  1,  1,  0,  1], dtype=torch.uint8),
 tensor([ 0,  0,  1,  1,  0,  1,  1,  0,  1], dtype=torch.uint8),
 tensor([ 0,  0,  1,  1,  0,  1,  1,  0,  1], dtype=torch.uint8),
 tensor([ 0,  0,  1,  1,  0,  1,  1,  0,  1], dtype=torch.uint8),
 tensor([ 0,  0,  1,  1,  1,  1,  1,  0,  1], dtype=torch.uint8),
 tensor([ 0,  0,  1,  1,  1,  0,  1,  0,  1], dtype=torch.uint8),
 tensor([ 0,  0,  1,  1,  1,  0,  1,  0,  1], dtype=torch.uint8),
 tensor([ 0,  0,  1,  1,  1,  0,  1,  1,  1], dtype=torch.uint8),
 tensor([ 0,  0,  1,  1,  1,  0,  1,  1,  0], dtype=torch.uint8)]